Apply ignore area to all images from selected ignore area from details page.
Visual-Regression-Tracker/frontend pull request #202
Opened 2021-06-21 22:10 UTC by suratdas

https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/276 
Attached video. Will raise backend pull request if this is approved. Currently, it is not possible to select which test runs it needs to apply to.

https://user-images.githubusercontent.com/9042580/122833949-9e75fe80-d2a2-11eb-9116-be2fa6651b89.mov

2021-07-01 09:40 UTC, pashidlos commented
@suratdas sorry for delay
I changed API to support bulk operations 
not you could utilise `POST test-runs/ignoreAreas/add`

2021-07-02 04:26 UTC, suratdas commented
> @suratdas sorry for delay
> I changed API to support bulk operations
> not you could utilise `POST test-runs/ignoreAreas/add`

I have included the latest changes now.

2021-07-02 15:52 UTC, pashidlos requested changes

2021-07-02 15:52 UTC, pashidlos commented on src/components/TestDetailsModal.tsx
> +    return ignoreAreaToReturn;
could be replaced with `find` as only one is needed 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

2021-07-02 15:52 UTC, pashidlos commented on src/components/TestDetailsModal.tsx
> +        allRows.forEach((value) => allIds.push(value.id));
you could make it with `map`
const allIds = allRows.map((item) => item.id);

2021-07-02 15:52 UTC, pashidlos commented on src/components/TestDetailsModal.tsx
> +      (allRows) => {
```suggestion
      (testRuns: TestRun[]) => {
```

2021-07-02 15:52 UTC, pashidlos commented on src/components/TestDetailsModal.tsx
> +    return ignoreAreaToReturn;
also handle the case if it's `undefined`

2021-07-02 15:52 UTC, pashidlos commented on src/components/TestDetailsModal.tsx
> +        testRunService.addIgnoreAreas(data).then(() => {
add error case handling

2021-07-03 13:03 UTC, pashidlos approved these changes
LGTM

2021-07-03 13:06 UTC, merged

2021-07-03 13:06 UTC, pashidlos commented
@suratdas thanks for contribution!